### ISSUE TITLE
Why does `scan_port_addr` hang on few addresses but not all?

### ISSUE THREAD

**Issue by weezy20** [notkild/port_scanner-rs#3]
I've been trying out `scan_port_addr` on two of my servers and one of them was scanned instantly, returning me the correct result of which ports were open. However with the same code, on another similar server, the process could continue `Running ... ` indefinitely until I had to `Ctrl - C` it. What could be the reason for this to happen?

**Comment by babariviere** [comment]
Hello,

One reason for this could be your firewall.
There is a rule in the firewall to `drop` the packet without informing it to the client.
A good 

Since there is no timeout in my library (which is not maintained, I apologize for that), this will hang indefinitely until you kill the process.

I hope this answer your question!
